//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Web_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHorasActividades
    {
        public int HorAct_IdHoras { get; set; }
        [Display(Name ="Fecha")]
        [DataType(DataType.Date),DisplayFormat(DataFormatString = "{0:dd/MM/yy}",ApplyFormatInEditMode = true)]
        public System.DateTime HorAct_Fecha { get; set; }
        [Display(Name ="Cantidad Horas")]
        public int HorAct_CantidadHoras { get; set; }
        public int HorAct_IdActividad { get; set; }
    
        public virtual tblActividades tblActividades { get; set; }
    }
}
